name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'  # Specify the distribution type here
        architecture: 'x64'
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        overwrite-settings: true

    - name: Set up Chrome WebDriver
      run: |
        LATEST_CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3 | cut -d '.' -f 1)
        LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$LATEST_CHROME_VERSION)
        curl -L -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /tmp
        chmod +x /tmp/chromedriver
        sudo mv /tmp/chromedriver /usr/local/bin/chromedriver

    - name: Build and test with Maven
      run: |
        mvn -B verify

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

