name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Use Windows runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        architecture: 'x64'
        server-id: 'github'
        server-username: ${{ github.actor }}
        server-password: ${{ github.token }}
        overwrite-settings: true

    - name: Set up Chromedriver for Windows
      run: |
        # Replace this with the correct Chromedriver version for your Chrome version
        $LATEST_CHROMEDRIVER_VERSION = "93.0.4577.63"  # Example version; replace with your Chrome version

        # Download Chromedriver
        Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_win32.zip" -OutFile "$env:TEMP\chromedriver.zip"

        # Extract Chromedriver
        Expand-Archive -Path "$env:TEMP\chromedriver.zip" -DestinationPath "$env:TEMP"
        
        # Move Chromedriver to a location in PATH
        Move-Item -Path "$env:TEMP\chromedriver.exe" -Destination "C:\Windows"

    - name: Build and test with Maven
      run: mvn -B verify

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports


