name: Selenium Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Set up Chrome WebDriver
      run: |
        LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -L -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip /tmp/chromedriver.zip -d /tmp
        chmod +x /tmp/chromedriver
        sudo mv /tmp/chromedriver /usr/local/bin/chromedriver

    - name: Build and test with Maven
      run: mvn -B verify

